### ISSUE TITLE
Roles you don't have still show up in the Common Header App Navigation

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#469]
<b>How it works now:</b>
Log in as a user who does NOT have the roles of Display Administrator, Content Editor or Content Publisher. Notice that in the CH App Navigation menu, they still see the options for Displays and Editor. They can click on those options, and go to the appropriate pages, and make changes to Presentations and Displays (even though they don't save). However this is still really confusing to the user. 

FYI if they log into the rva.risevision.com, they don't see those pages.

For further clarification: https://dl.dropboxusercontent.com/u/8237394/Screencasts/2015-02-26_0925.swf

<b>How it should work:</b>
If a user does not have a specific role, the actions associated with that role should not show in the CH App Navigation menu.

**Comment by ByronDarlison** [comment]
@alex-deaconu @robb-price @brianloosbrock I believe this issue is now closed. Do you guys concur?

**Comment by alex-deaconu** [comment]
@ByronDarlison @robb-price @brianloosbrock nope. This particular functionality was never implemented. All Apps show in the launcher despite the Users' roles.

However with the new Apps we've revised the way we handle roles. We let the User access the list and the item, however remove the ability to Save/Delete/etc if they don't have that particular role.

So, I would venture to say this issue is not as relevant anymore and can be closed. Thoughts? Thanks!

**Comment by ByronDarlison** [comment]
@alex-deaconu agreed. Let's see if it comes up with anyone and if they have a strong case for why it should be different we will address then. Thanks
