### ISSUE TITLE
The intercom chat bubble is showing on all pages, including when logged in with a user that does not have priority support.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#617]
<b>How it works now:</b>
1. Go to apps.risevision.com, store.risevision.com, or www.risevision.com, and notice that the Intercom chat bubble shows on all pages and you can ask questions in it.
2. Log into store.risevision.com or apps.risevision.com as a user who does not have priority support. Notice that you can ask questions in the chat bubble without having to purchase or start a trial for priority support.

For further clarification: https://goo.gl/Aew6pi

<b>How it should work:</b>
The Intercom chat bubble should not be present on any page. The only way to access Intercom chat is to log into a Company that has Priority Support either subscribed or trial, click Need Help, and then select Priority Support.

**Comment by alex-deaconu** [comment]
@robb-price took a look at the Intercom Messenger settings (https://app.intercom.io/a/apps/d85f4ah4/settings/messenger) and it seems the Chat Bubble is enabled for our account: http://screencast.com/t/kv9gwmIh. Is this something that was changed recently? I believe the bubble should be hidden (`Visitors on your website` checkbox unchecked) since we manually enable it for Apps that require it. 

Thanks.

**Comment by robb-price** [comment]
@alex-deaconu Wasn't changed by anyone in CS, and Intercom can't tell if this was changes recently or not by us. I wasn't sure if it was supposed to be checked or not, so I wanted to ask before changing anything.

I will uncheck it to see if this corrects the behaviour.

**Comment by alex-deaconu** [comment]
@robb-price sounds good. Thanks.

**Comment by ByronDarlison** [comment]
@robb-price can you confirm if this is closed?

**Comment by robb-price** [comment]
@ByronDarlison @alex-deaconu @ezequielc Confirmed that this has solved the issue. Verified and closed.
