### ISSUE TITLE
User who you click on has no User Details, and cannot be deleted

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/common-header#629]
<b>How it works now:</b>
1. Go to this Company: https://apps.risevision.com/?cid=e9e79b4e-5513-4e06-b4be-df984bd9fe3f.
2. Open the user details for the user MDC Partners AP DEPT (ITProceurements@mdc-partners.com)
3. Notice that there are no User Details, and you cannot delete this user.

For further clarification: https://goo.gl/hKMuJa

<b>How it should work:</b>
You should be able to delete any user that you add to a Company.

**Comment by ezequielc** [comment]
@olegrise @alexey-rise You may have faced something similar when working on PR https://github.com/Rise-Vision/core/pull/243 so I want your input here.

In current issue, when the user list is requested, it returns one user with uppercase letters in the ID ("ITProcurement@mdc-partners.com").  When we try to get the user, a 404 User Not Found error is returned. The changedBy is set to System, that is why I imagine it is related to the ImportUsers task.

My guess is that the ID was indexed with uppercase, but whenever we try to get the user, we change the requested username to lowercase (https://github.com/Rise-Vision/core/blob/c845a9ed9b3cafc9d7dd1e90fb165865b4850b88/src/main/java/com/risevision/core/data/User.java#L400), therefore no user is found. 

If that is the case, should we change the code to not force lowercase? Or, as it seems an exceptional case, could we update the ID somehow? Any other suggestions? Thanks

**Comment by alexey-rise** [comment]
@ezequielc Hmm, I thought I deleted all the mixed case users when we had that issue and then reimported them correctly. Looks like it was imported even earlier and that's how I missed it.

To fix: use a spacial version of the Core I deployed when I was fixing this issue earlier and delete the user and then re-create it: https://apis-explorer.appspot.com/apis-explorer/?base=https%3A%2F%2Ffix-dot-rvaserver2.appspot.com%2F_ah%2Fapi#p/core/v1/core.user.delete (this version doesn't convert input to lowercase when deleting).

We **cannot** change the code not to force the lowercase because AppEngine DB is case sensitive and emails are not and we cannot predict how the user types their email when they login into Google (e.g. we they can type itProcurement@mdc-partners.com one day and ItpRocurement@mdc-partners.com the other day and we need to look up the same user in both cases).

**Comment by ezequielc** [comment]
Thanks @alexey-rise ! I agree with your comments. I will use the special version to delete and recreate the user. 

@robb-price Do you see any problems with that? Can I proceed deleting and recreating the user? Thanks

**Comment by robb-price** [comment]
@ezequielc Nope, feel free.

Thanks!

**Comment by ezequielc** [comment]
Thanks @robb-price ! I will work on that. Cheers

**Comment by ezequielc** [comment]
@robb-price user was deleted and recreated. Please validate. Thanks!

**Comment by robb-price** [comment]
Validated and closed.

Thanks!
